# Generated by Django 4.1.5 on 2023-03-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakib', '0004_productlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.AddField(
            model_name='productlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='productlist',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlist',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
