# Generated by Django 4.1.5 on 2023-03-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakib', '0005_delete_product_productlist_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='category',
            field=models.CharField(blank=True, choices=[('Fast_Food', 'Fast_Food'), ('Chicken_Item', 'Chicken_Item'), ('Beef_Item', 'Beef_Item'), ('Fish_Item', 'Fish_Item')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='quantity_Type',
            field=models.CharField(blank=True, choices=[('pice', 'pice'), ('plate', 'plate')], max_length=100),
        ),
    ]
