# Generated by Django 4.1.5 on 2023-03-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakib', '0006_productlist_category_productlist_quantity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='quantity_Type',
            field=models.CharField(blank=True, choices=[('piece', 'piece'), ('p', 'plate')], max_length=100),
        ),
    ]
