# Generated by Django 4.1.5 on 2023-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakib', '0007_alter_productlist_quantity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='quantity_Type',
            field=models.CharField(blank=True, choices=[('piece', 'piece'), ('plate', 'plate')], default='piece', max_length=100),
        ),
    ]
